---
latitude: 25.287183
longitude: 51.543838999999934
map_zoom: 12
name: Plaza Inn Doha
email: info@plazainn.com.qa
phone_number: "+974 4422 1111"
default_currency: QAR
address: PO Box 22920, Doha, Qatar
_hotel_id: PLAIND
_portal_id: plazainndoha
_root_path: https://rt3api-prd-ase.ttaws.com
_ttweb_plugins_version: v2
logo: <img id="1518689611970" class=" " src="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-15-051332/LOGO.jpg"
  data-image-large="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-15-051332/large_LOGO.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-15-051332/medium_LOGO.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-15-051332/small_LOGO.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-15-051332/xsmall_LOGO.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-15-051332/thumb_LOGO.jpg"
  />&nbsp;<!-- <img id="1500298438159" class=" " src="https://s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_120_512/media/2017-07-17-093113/logo.jpg"
  data-mce-src="https://s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_120_512/media/2017-07-17-093113/logo.jpg"
  data-mce-selected="1"> //-->
footer_logo: '<img id="1518166383577" class=" " style="display: block; margin-left:
  auto; margin-right: auto; float: left;" src="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-09-035241/LOGO.jpg"
  width="138" height="178" data-image-large="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-09-035241/large_LOGO.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-09-035241/medium_LOGO.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-09-035241/small_LOGO.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-09-035241/xsmall_LOGO.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-09-035241/thumb_LOGO.jpg"
  />'
footer_last_column: <img id="1518620625485" class=" " src="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-14-100344/member-of-international-hospitality.jpg"
  width="370" height="108" data-image-large="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-14-100344/large_member_of_international_hospitality.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-14-100344/medium_member_of_international_hospitality.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-14-100344/small_member_of_international_hospitality.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-14-100344/xsmall_member_of_international_hospitality.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/418_810_7990/media/2018-02-14-100344/thumb_member_of_international_hospitality.jpg"
  />
