---
latitude: 
longitude: 
map_zoom: 12
name: 
email: 
phone_number: 
address: 
_hotel_id: PLAIND
_portal_id: plazainndoha
_root_path: https://rt3api-prd-ase.ttaws.com
logo: <img id="1507630205316" class=" " src="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-061002/Screen-Shot-2017-10-10-at-11.09.17-am.png"
  data-image-large="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-061002/large_Screen_Shot_2017-10-10_at_11.09.17_am.png"
  data-image-medium="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-061002/medium_Screen_Shot_2017-10-10_at_11.09.17_am.png"
  data-image-small="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-061002/small_Screen_Shot_2017-10-10_at_11.09.17_am.png"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-061002/xsmall_Screen_Shot_2017-10-10_at_11.09.17_am.png"
  data-image-thumb="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-061002/thumb_Screen_Shot_2017-10-10_at_11.09.17_am.png"
  />&nbsp;<!-- <img id="1500298438159" class=" " src="https://s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_120_512/media/2017-07-17-093113/logo.jpg"
  data-mce-src="https://s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_120_512/media/2017-07-17-093113/logo.jpg"
  data-mce-selected="1"> //-->
