---
latitude: 
longitude: 
map_zoom: 12
name: 
email: 
phone_number: 
address: 
_hotel_id: PLAIND
_portal_id: plazainndoha
_root_path: https://rt3api-prd-ase.ttaws.com
logo: <img id="1507629499825" class=" " src="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-055817/logo.jpg"
  data-image-large="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-055817/large_logo.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-055817/medium_logo.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-055817/small_logo.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-055817/xsmall_logo.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/418_810_7990/media/2017-10-10-055817/thumb_logo.jpg"
  /><!-- HOTEL NAME //--> <!-- <img id="1500298438159" class=" " src="https://s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_120_512/media/2017-07-17-093113/logo.jpg"
  data-mce-src="https://s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_120_512/media/2017-07-17-093113/logo.jpg"
  data-mce-selected="1"> //-->
